description: A custom weightset for mystery to fit what I like playing with the added fun of figuring out the settings
glitches_required:
  none: 100
  overworld_glitches: 0
  major_glitches: 0
  no_logic: 0
item_placement:
  basic: 0
  advanced: 100
dungeon_items:
  standard: 55
  mc: 10
  mcs: 10
  full: 25
accessibility:
  items: 50
  locations: 50
  none: 0
goals:
  ganon: 35
  fast_ganon: 25
  dungeons: 5
  pedestal: 17.5
  triforce-hunt: 17.5
tower_open:
  '0': 0
  '1': 0
  '2': 0
  '3': 0
  '4': 0
  '5': 0
  '6': 0
  '7': 65
  random: 35
ganon_open:
  '0': 0
  '1': 0
  '2': 0
  '3': 0
  '4': 0
  '5': 0
  '6': 0
  '7': 65
  random: 65
world_state:
  standard: 35
  open: 50
  inverted: 15
  retro: 0
entrance_shuffle:
  none: 75
  simple: 0
  restricted: 0
  full: 10
  crossed: 15
  insanity: 0
boss_shuffle:
  none: 99
  simple: 0
  full: 0
  random: 1
enemy_shuffle:
  none: 99
  shuffled: 0
  random: 1
hints:
  'on': 50
  'off': 50
weapons:
  randomized: 45
  assured: 45
  vanilla: 10
  swordless: 0
item_pool:
  normal: 100
  hard: 0
  expert: 0
  crowd_control: 0
item_functionality:
  normal: 100
  hard: 0
  expert: 0
enemy_damage:
  default: 100
  shuffled: 0
  random: 0
enemy_health:
  default: 100
  easy: 0
  hard: 0
  expert: 0
